# Epic 2 Test Configuration - Minimal Features
# For testing baseline performance with minimal EPIC 2 features

# Document processor for handling input files
document_processor:
  type: "hybrid_pdf"
  config:
    chunk_size: 1024
    chunk_overlap: 128

# Embedding generator for converting text to vectors  
embedder:
  type: "modular"
  config:
    model:
      type: "sentence_transformer"
      config:
        model_name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
        device: "mps"
        normalize_embeddings: true
    batch_processor:
      type: "dynamic"
      config:
        initial_batch_size: 64
        max_batch_size: 256
        optimize_for_memory: false
    cache:
      type: "memory"
      config:
        max_entries: 100000
        max_memory_mb: 1024

# Epic 2 ModularUnifiedRetriever with Minimal Features
retriever:
  type: "modular_unified"
  config:
    vector_index:
      type: "faiss"
      config:
        index_type: "IndexFlatIP"
        normalize_embeddings: true
        metric: "cosine"
    
    sparse:
      type: "bm25"
      config:
        k1: 1.2
        b: 0.25  # Fixed: reduced from 0.75 to reduce document length bias
        lowercase: true
        preserve_technical_terms: true
    
    # Standard RRF fusion (no graph enhancement)
    fusion:
      type: "rrf"
      config:
        k: 30  # Fixed: reduced from 60 to increase score discriminative power
        weights:
          dense: 0.8  # Fixed: increased from 0.6 to favor working dense component
          sparse: 0.2  # Fixed: reduced from 0.4 to reduce impact of biased BM25
        graph_enabled: false
    
    # Identity reranker (no neural reranking)
    reranker:
      type: "identity"
      config:
        enabled: false

# Answer generation strategy
answer_generator:
  type: "adaptive_modular"
  config:
    llm_client:
      type: "mock"
      config:
        response_pattern: "technical"
        include_citations: true
        max_response_length: 1024
        mock_delay: 0.1
    temperature: 0.3
    max_tokens: 1024
    confidence_threshold: 0.85
    
    prompt_builder:
      type: "simple"
      config:
        max_context_length: 12000
        include_instructions: true
        citation_style: "inline"

# Global settings
global_settings:
  environment: "testing"
  log_level: "info"