# RAG Pipeline Configuration
# This file defines the components and settings for the RAG pipeline

# Document processor for handling input files
document_processor:
  type: "hybrid_pdf"  # Options: hybrid_pdf, simple_pdf
  config:
    chunk_size: 1024
    chunk_overlap: 128

# Embedding generator for converting text to vectors
embedder:
  type: "sentence_transformer"  # Options: sentence_transformer, openai
  config:
    model_name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
    use_mps: true

# Retrieval strategy (Modular Architecture)
retriever:
  type: "modular_unified"  # Modular: decomposed into sub-components for better architecture compliance
  config:
    vector_index:
      type: "faiss"
      config:
        index_type: "IndexFlatIP"
        normalize_embeddings: true
        metric: "cosine"
    sparse:
      type: "bm25"
      config:
        k1: 1.2
        b: 0.75
        lowercase: true
        preserve_technical_terms: true
    fusion:
      type: "rrf"
      config:
        k: 60
        weights:
          dense: 0.7
          sparse: 0.3
    reranker:
      type: "identity"
      config:
        enabled: true

# Answer generation strategy (Local Ollama)
answer_generator:
  type: "adaptive_modular"  # Options: adaptive, adaptive_modular, simple, chain_of_thought
  config:
    model_name: "llama3.2:3b"  # Local Ollama model
    api_token: null
    temperature: 0.3
    max_tokens: 512
    use_ollama: true
    ollama_url: "http://localhost:11434"
    use_inference_providers: false
    enable_adaptive_prompts: false
    enable_chain_of_thought: false
    confidence_threshold: 0.85

# Global settings (optional)
global_settings: {}
