# Demo RAG Configuration
# Optimized for demonstrations with balanced features and performance
# Uses MockLLMAdapter for reliable demo without dependencies

# Document processor optimized for demo
document_processor:
  type: "hybrid_pdf"
  config:
    chunk_size: 768
    chunk_overlap: 96

# Demo-optimized embedder
embedder:
  type: "modular"
  config:
    model:
      type: "sentence_transformer"
      config:
        model_name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
        device: "mps"
        normalize_embeddings: true
    batch_processor:
      type: "dynamic"
      config:
        initial_batch_size: 32
        max_batch_size: 128
        optimize_for_memory: true
    cache:
      type: "memory"
      config:
        max_entries: 75000
        max_memory_mb: 768

# Demo retriever with selective Epic 2 features
retriever:
  type: "modular_unified"
  config:
    vector_index:
      type: "faiss"
      config:
        index_type: "IndexFlatIP"
        normalize_embeddings: true
        metric: "cosine"
    
    sparse:
      type: "bm25"
      config:
        k1: 1.2
        b: 0.75
        lowercase: true
        filter_stop_words: true
        stop_word_sets: ["english_common"]
        preserve_technical_terms: true
    
    # Use neural reranking for demo (shows Epic 2 capability)
    fusion:
      type: "rrf"
      config:
        k: 60
        weights:
          dense: 0.6
          sparse: 0.4
    
    # Epic 2 Feature: Neural reranking enabled for demo
    reranker:
      type: "neural"
      config:
        enabled: true
        model_name: "cross-encoder/ms-marco-MiniLM-L6-v2"
        device: "mps"
        batch_size: 16
        max_length: 256
        max_candidates: 50
        models:
          default_model:
            name: "cross-encoder/ms-marco-MiniLM-L6-v2"
            device: "mps"
            batch_size: 16
            max_length: 256
        default_model: "default_model"

# Demo answer generation - Multiple LLM options
answer_generator:
  type: "adaptive_modular"
  config:
    # Current: Mock LLM for reliable demo without dependencies (uncomment to use)
    # llm_client:
    #   type: "mock"
    #   config:
    #     response_pattern: "technical"
    #     include_citations: true
    #     max_response_length: 768
    #     mock_delay: 0.1
    #     demo_mode: true
    
    # Alternative 1: Local Ollama LLM (comment out others, uncomment this)
    # llm_client:
    #   type: "ollama"
    #   config:
    #     model_name: "llama3.2:3b"
    #     base_url: "http://localhost:11434"
    #     timeout: 30
    #     max_retries: 3
    
    # Alternative 2: HuggingFace API LLM (currently active)
    llm_client:
      type: "huggingface"
      config:
        model_name: "microsoft/DialoGPT-medium"
        api_token: "${HF_TOKEN}"  # Set HF_TOKEN environment variable
        timeout: 30
        use_chat_completion: true
        fallback_models:
          - "google/gemma-2-2b-it"
          - "google/flan-t5-small"
        max_tokens: 768
        temperature: 0.1
        top_p: 0.9
    
    temperature: 0.3
    max_tokens: 768
    confidence_threshold: 0.75
    
    prompt_builder:
      type: "simple"
      config:
        max_context_length: 10000
        include_instructions: true
        citation_style: "inline"
    
    response_parser:
      type: "markdown"
      config:
        preserve_formatting: true
        extract_citations: true
    
    confidence_scorer:
      type: "semantic"
      config:
        relevance_weight: 0.4
        grounding_weight: 0.4
        quality_weight: 0.2
        min_answer_length: 20
        max_answer_length: 1000

# Demo-optimized global settings
global_settings:
  log_level: "INFO"
  cache_enabled: true
  performance_monitoring: true
  max_concurrent_requests: 6