# Demo RAG Configuration
# Optimized for demonstrations with balanced features and performance
# Uses MockLLMAdapter for reliable demo without dependencies

# Document processor optimized for demo
document_processor:
  type: "hybrid_pdf"
  config:
    chunk_size: 768
    chunk_overlap: 96

# Demo-optimized embedder
embedder:
  type: "modular"
  config:
    model:
      type: "sentence_transformer"
      config:
        model_name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
        device: "mps"
        normalize_embeddings: true
    batch_processor:
      type: "dynamic"
      config:
        initial_batch_size: 32
        max_batch_size: 128
        optimize_for_memory: true
    cache:
      type: "memory"
      config:
        max_entries: 75000
        max_memory_mb: 768

# Demo retriever with selective Epic 2 features
retriever:
  type: "modular_unified"
  config:
    vector_index:
      type: "faiss"
      config:
        index_type: "IndexFlatIP"
        normalize_embeddings: true
        metric: "cosine"
    
    sparse:
      type: "bm25"
      config:
        k1: 1.2
        b: 0.75
        lowercase: true
        filter_stop_words: true
        stop_word_sets: ["english_common"]
        preserve_technical_terms: true
    
    # Use neural reranking for demo (shows Epic 2 capability)
    fusion:
      type: "rrf"
      config:
        k: 60
        weights:
          dense: 0.6
          sparse: 0.4
    
    # Epic 2 Feature: Neural reranking enabled for demo
    reranker:
      type: "neural"
      config:
        enabled: true
        model_name: "cross-encoder/ms-marco-MiniLM-L6-v2"
        device: "mps"
        batch_size: 16
        max_length: 256
        max_candidates: 50
        models:
          default_model:
            name: "cross-encoder/ms-marco-MiniLM-L6-v2"
            device: "mps"
            batch_size: 16
            max_length: 256
        default_model: "default_model"

# Demo answer generation with MockLLMAdapter for reliability
answer_generator:
  type: "adaptive_modular"
  config:
    llm_client:
      type: "mock"
      config:
        response_pattern: "technical"
        include_citations: true
        max_response_length: 768
        mock_delay: 0.1
        demo_mode: true
    temperature: 0.3
    max_tokens: 768
    confidence_threshold: 0.75
    
    prompt_builder:
      type: "simple"
      config:
        max_context_length: 10000
        include_instructions: true
        citation_style: "inline"
    
    response_parser:
      type: "markdown"
      config:
        preserve_formatting: true
        extract_citations: true
    
    confidence_scorer:
      type: "semantic"
      config:
        relevance_weight: 0.4
        grounding_weight: 0.4
        quality_weight: 0.2
        min_answer_length: 20
        max_answer_length: 1000

# Demo-optimized global settings
global_settings:
  log_level: "INFO"
  cache_enabled: true
  performance_monitoring: true
  max_concurrent_requests: 6