# Epic 2 Test Configuration - Neural Reranking Enabled
# For testing neural reranking features specifically

# Document processor for handling input files
document_processor:
  type: "hybrid_pdf"
  config:
    chunk_size: 1024
    chunk_overlap: 128

# Embedding generator for converting text to vectors  
embedder:
  type: "modular"
  config:
    model:
      type: "sentence_transformer"
      config:
        model_name: "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
        device: "auto"
        normalize_embeddings: true
    batch_processor:
      type: "dynamic"
      config:
        initial_batch_size: 64
        max_batch_size: 256
        optimize_for_memory: false
    cache:
      type: "memory"
      config:
        max_entries: 100000
        max_memory_mb: 1024

# Epic 2 ModularUnifiedRetriever with Neural Reranking Enabled
retriever:
  type: "modular_unified"
  config:
    vector_index:
      type: "faiss"
      config:
        index_type: "IndexFlatIP"
        normalize_embeddings: true
        metric: "cosine"
    
    sparse:
      type: "bm25"
      config:
        k1: 1.2
        b: 0.75
        lowercase: true
        preserve_technical_terms: true
    
    # Standard RRF fusion (graph disabled for neural-only testing)
    fusion:
      type: "rrf"
      config:
        k: 60
        weights:
          dense: 0.6
          sparse: 0.4
        graph_enabled: false
    
    # Epic 2 Feature: Neural Reranking - ENABLED
    reranker:
      type: "neural"
      config:
        enabled: true
        model_name: "cross-encoder/ms-marco-MiniLM-L6-v2"
        device: "auto"
        batch_size: 32
        max_length: 512
        max_candidates: 100
        models:
          default_model:
            name: "cross-encoder/ms-marco-MiniLM-L6-v2"
            device: "auto"
            batch_size: 32
            max_length: 512
        default_model: "default_model"

# Answer generation strategy
answer_generator:
  type: "adaptive_modular"
  config:
    model_name: "llama3.2:3b"
    api_token: null
    temperature: 0.3
    max_tokens: 1024
    use_ollama: true
    ollama_url: "http://localhost:11434"
    use_inference_providers: false
    enable_adaptive_prompts: false
    enable_chain_of_thought: false
    confidence_threshold: 0.85
    
    prompt_builder:
      type: "simple"
      config:
        max_context_length: 12000
        include_instructions: true
        citation_style: "inline"

# Global settings
global_settings:
  environment: "testing"
  log_level: "info"